### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by pinguinjkeke** [pinguinjkeke/vue-local-storage#11]
- [x] Fix some const/let statements in es2015 version
- [x] Add default value to ```get``` method
- [x] Add unit tests
- [ ] Add e2e tests
- [x] Split to src and dist folders
- [x] Add building with rollup
- [ ] Add examples
- [ ] Add TypeScript bindings
- [x] Add eslint rules
- [x] Add ability to change $localStorage binding to any other name
- [ ] Documentation (gitbook maybe)
- [ ] Changelog
- [x] Integrate with CI
- [ ] Switch to JSON.stringify and JSON.parse instead of manual fields definition
- [x] SSR support
- [x] Automatically create getters and setters (Thanks to @dasdeck)
- [x] Namespaces (Thanks to @nikolay-borzov)

**Comment by Fohlen** [comment]
You should definitely add `sessionStorage` to this list.

**Comment by himself65** [comment]
need help? I can help to support `typescript` types binding
